import Foundation
import Testing
#if canImport(AdmitPathLogic)
@testable import AdmitPathLogic
#elseif canImport(AdmitPath)
@testable import AdmitPath
#endif

struct DeadlineServiceTests {
    @Test
    func plannerItemsIncludeCatalogAndTaskMilestones() {
        let service = DeadlineService()
        let tasks = [
            ApplicationTask(id: "task_1", applicationID: "app_1", title: "Draft SOP", dueDate: .now, taskType: .sop, isCompleted: false, isAutoGenerated: true)
        ]
        let deadline = ProgramDeadline(
            id: "deadline_1",
            programID: "program_1",
            intakeTerm: "Fall 2027",
            applicationDeadline: .now.addingTimeInterval(60 * 60 * 24 * 20),
            scholarshipDeadline: .now.addingTimeInterval(60 * 60 * 24 * 10),
            depositDeadline: .now.addingTimeInterval(60 * 60 * 24 * 40)
        )

        let items = service.plannerItems(applicationID: "app_1", tasks: tasks, deadline: deadline)

        #expect(items.contains(where: { $0.type == .documentTask }))
        #expect(items.contains(where: { $0.type == .applicationDeadline }))
        #expect(items.contains(where: { $0.type == .scholarshipDeadline }))
        #expect(items.contains(where: { $0.type == .depositDeadline }))
    }
}
