import Foundation
import Testing
#if canImport(AdmitPathLogic)
@testable import AdmitPathLogic
#elseif canImport(AdmitPath)
@testable import AdmitPath
#endif

struct TaskGenerationServiceTests {
    @Test
    func generatedTasksReflectRequirementsAndScholarshipNeed() {
        let requirement = ProgramRequirement(
            id: "req",
            programID: "program",
            minGPAValue: 3.0,
            minGPAScale: 4.0,
            ieltsMin: 6.5,
            toeflMin: 88,
            duolingoMin: 120,
            sopRequired: true,
            cvRequired: true,
            lorCount: 2,
            transcriptRequired: true,
            passportRequired: true
        )
        let profile = StudentProfile(
            id: "student_test",
            fullName: "Nadia",
            nationality: "Bangladesh",
            currentCountry: "Bangladesh",
            targetIntake: "Fall 2027",
            degreeLevel: .masters,
            subjectArea: "Finance",
            gpaValue: 3.8,
            gpaScale: 4.0,
            englishTestType: .ielts,
            englishTestScore: 7.5,
            workExperienceYears: 2,
            scholarshipNeeded: true,
            annualBudgetUSD: 32000,
            tuitionBudgetUSD: 22000,
            preferredCountries: ["United Kingdom"],
            onboardingComplete: true
        )
        let deadline = Date().addingTimeInterval(60 * 60 * 24 * 50)
        let tasks = TaskGenerationService().generateTasks(
            applicationID: "app_program",
            requirement: requirement,
            deadline: deadline,
            profile: profile
        )

        #expect(tasks.contains(where: { $0.taskType == ApplicationTaskType.transcript }))
        #expect(tasks.contains(where: { $0.taskType == ApplicationTaskType.cv }))
        #expect(tasks.filter { $0.taskType == ApplicationTaskType.lor }.count == 2)
        #expect(tasks.contains(where: { $0.taskType == ApplicationTaskType.financialProof }))
        #expect(tasks.contains(where: { $0.taskType == ApplicationTaskType.scholarshipEssay }))
        #expect(tasks.contains(where: { $0.taskType == ApplicationTaskType.submit }))
    }

    @Test
    func completionPercentUsesExpandedWeights() {
        let service = TaskGenerationService()
        let tasks: [ApplicationTask] = [
            ApplicationTask(id: "t1", applicationID: "app", title: "Transcript", dueDate: .now, taskType: .transcript, isCompleted: true, isAutoGenerated: true),
            ApplicationTask(id: "t2", applicationID: "app", title: "CV", dueDate: .now, taskType: .cv, isCompleted: true, isAutoGenerated: true),
            ApplicationTask(id: "t3", applicationID: "app", title: "SOP", dueDate: .now, taskType: .sop, isCompleted: false, isAutoGenerated: true),
            ApplicationTask(id: "t4", applicationID: "app", title: "Scholarship Essay", dueDate: .now, taskType: .scholarshipEssay, isCompleted: true, isAutoGenerated: true),
            ApplicationTask(id: "t5", applicationID: "app", title: "LOR 1", dueDate: .now, taskType: .lor, isCompleted: true, isAutoGenerated: true),
            ApplicationTask(id: "t6", applicationID: "app", title: "LOR 2", dueDate: .now, taskType: .lor, isCompleted: false, isAutoGenerated: true),
            ApplicationTask(id: "t7", applicationID: "app", title: "Financial Proof", dueDate: .now, taskType: .financialProof, isCompleted: true, isAutoGenerated: true),
            ApplicationTask(id: "t8", applicationID: "app", title: "Review form", dueDate: .now, taskType: .applicationForm, isCompleted: true, isAutoGenerated: true),
            ApplicationTask(id: "t9", applicationID: "app", title: "Submit", dueDate: .now, taskType: .submit, isCompleted: false, isAutoGenerated: true)
        ]

        #expect(service.completionPercent(for: tasks) == 72)
    }
}
