import Foundation

struct ApplicationRecord: Codable, Hashable, Identifiable {
    var id: String
    var programID: String
    var universityName: String
    var programName: String
    var country: String = ""
    var status: ApplicationStatus
    var completionPercent: Int
    var notes: String
    var linkedScholarshipIDs: [String] = []
    var createdAt: Date
    var targetDeadline: Date
}

struct ApplicationTask: Codable, Hashable, Identifiable {
    var id: String
    var applicationID: String
    var title: String
    var dueDate: Date
    var taskType: ApplicationTaskType
    var isCompleted: Bool
    var isAutoGenerated: Bool
    var notes: String = ""
}

struct PlannerItem: Codable, Hashable, Identifiable {
    var id: String
    var applicationID: String
    var title: String
    var date: Date
    var type: PlannerMilestoneType
    var source: PlannerSource
    var notes: String
    var isCompleted: Bool
}

struct DocumentChecklistItem: Identifiable, Hashable {
    let type: DocumentType
    let isReady: Bool
    let supportingNote: String

    var id: String { type.rawValue }
}
