import Foundation

struct DeadlineService {
    func nextDeadline(from applications: [ApplicationRecord]) -> ApplicationRecord? {
        applications
            .filter { $0.targetDeadline >= Date() }
            .sorted { $0.targetDeadline < $1.targetDeadline }
            .first
            ?? applications.sorted { $0.targetDeadline < $1.targetDeadline }.first
    }

    func dueSoonTasks(from tasks: [ApplicationTask], limit: Int = 5) -> [ApplicationTask] {
        tasks
            .filter { !$0.isCompleted }
            .sorted { $0.dueDate < $1.dueDate }
            .prefix(limit)
            .map { $0 }
    }

    func plannerItems(
        applicationID: String,
        tasks: [ApplicationTask],
        deadline: ProgramDeadline
    ) -> [PlannerItem] {
        var items = tasks.map { task in
            PlannerItem(
                id: task.id,
                applicationID: applicationID,
                title: task.title,
                date: task.dueDate,
                type: plannerType(for: task.taskType),
                source: .autoGenerated,
                notes: task.notes,
                isCompleted: task.isCompleted
            )
        }

        items.append(
            PlannerItem(
                id: "\(applicationID)_application_deadline",
                applicationID: applicationID,
                title: "Application deadline",
                date: deadline.applicationDeadline,
                type: .applicationDeadline,
                source: .catalog,
                notes: deadline.notes,
                isCompleted: false
            )
        )

        if let scholarshipDeadline = deadline.scholarshipDeadline {
            items.append(
                PlannerItem(
                    id: "\(applicationID)_scholarship_deadline",
                    applicationID: applicationID,
                    title: "Scholarship deadline",
                    date: scholarshipDeadline,
                    type: .scholarshipDeadline,
                    source: .catalog,
                    notes: "Plan funding applications before this date.",
                    isCompleted: false
                )
            )
        }

        if let depositDeadline = deadline.depositDeadline {
            items.append(
                PlannerItem(
                    id: "\(applicationID)_deposit_deadline",
                    applicationID: applicationID,
                    title: "Deposit deadline",
                    date: depositDeadline,
                    type: .depositDeadline,
                    source: .catalog,
                    notes: "Track the offer acceptance and deposit decision here.",
                    isCompleted: false
                )
            )
        }

        if let interviewWindowStart = deadline.interviewWindowStart {
            items.append(
                PlannerItem(
                    id: "\(applicationID)_interview_window",
                    applicationID: applicationID,
                    title: "Interview window opens",
                    date: interviewWindowStart,
                    type: .interviewWindow,
                    source: .catalog,
                    notes: "Use this as the prep start marker for likely interview routes.",
                    isCompleted: false
                )
            )
        }

        if let visaPrepStart = deadline.visaPrepStart {
            items.append(
                PlannerItem(
                    id: "\(applicationID)_visa_prep",
                    applicationID: applicationID,
                    title: "Visa prep checkpoint",
                    date: visaPrepStart,
                    type: .visaPrep,
                    source: .catalog,
                    notes: "Gather financial, passport, and decision documents early.",
                    isCompleted: false
                )
            )
        }

        return items.sorted { $0.date < $1.date }
    }

    func upcomingPlannerItems(from items: [PlannerItem], limit: Int = 5) -> [PlannerItem] {
        items
            .filter { !$0.isCompleted }
            .sorted { $0.date < $1.date }
            .prefix(limit)
            .map { $0 }
    }

    func suggestedNotifications(
        tasks: [ApplicationTask],
        applications: [ApplicationRecord],
        plannerItems: [PlannerItem],
        preferences: NotificationPreferences
    ) -> [NotificationItem] {
        var items: [NotificationItem] = []

        if preferences.deadlineReminders, let deadline = nextDeadline(from: applications) {
            items.append(
                NotificationItem(
                    id: "deadline_\(deadline.id)",
                    title: "Deadline approaching",
                    body: "\(deadline.universityName) is due on \(formatDate(deadline.targetDeadline)).",
                    scheduledFor: deadline.targetDeadline
                )
            )
        }

        if preferences.dailyTaskReminders, let task = dueSoonTasks(from: tasks, limit: 1).first {
            items.append(
                NotificationItem(
                    id: "task_\(task.id)",
                    title: "Task due soon",
                    body: "\(task.title) is due \(relativeDaysString(to: task.dueDate)).",
                    scheduledFor: task.dueDate
                )
            )
        }

        if preferences.scholarshipReminders,
           let scholarshipItem = upcomingPlannerItems(from: plannerItems, limit: 20).first(where: { $0.type == .scholarshipDeadline }) {
            items.append(
                NotificationItem(
                    id: "planner_\(scholarshipItem.id)",
                    title: "Scholarship checkpoint",
                    body: "\(scholarshipItem.title) is \(relativeDaysString(to: scholarshipItem.date)).",
                    scheduledFor: scholarshipItem.date
                )
            )
        }

        if preferences.weeklyProgressSummary {
            items.append(
                NotificationItem(
                    id: "weekly_summary",
                    title: "Weekly planning summary",
                    body: "\(upcomingPlannerItems(from: plannerItems, limit: 3).count) milestones need attention this week.",
                    scheduledFor: .now
                )
            )
        }

        return items.sorted { $0.scheduledFor < $1.scheduledFor }
    }

    private func plannerType(for taskType: ApplicationTaskType) -> PlannerMilestoneType {
        switch taskType {
        case .lor:
            return .recommender
        case .englishTest:
            return .testBooking
        case .transcript, .cv, .sop, .scholarshipEssay, .passport, .financialProof, .portfolio, .applicationForm, .applicationFee, .submit, .requirementsReview, .deposit, .visa, .interviewPrep, .custom:
            return .documentTask
        }
    }
}
